<?php
/**
 * @var $block \Magento\Checkout\Block\Cart
 * @var $viewModel \Searchspring\Tracking\ViewModel\CartViewModel
 */
?>
<?php $viewModel = $block->getData('searchspring_cart_view_model'); ?>
<?php $searchspringSiteId = $block->escapeHtmlAttr($viewModel->getSearchspringSiteId()); ?>

<script type="text/javascript">
    <?php if (!empty($searchspringSiteId) && !empty($this->getQuote()->getItems())): ?>
    <?php $products = $viewModel->getProducts($this->getQuote()->getItems()); ?>
    try {
        IntelliSuggest.init({
            siteId: '<?= $searchspringSiteId ?>',
            context: 'Basket',
            seed: [
                <?php foreach ($viewModel->getProductsSku() as $productSku): ?>
                '<?= $productSku ?>',
                <?php endforeach; ?>
            ]
        });
        <?php foreach ($products as $product): ?>
        IntelliSuggest.haveItem({
            sku: '<?= $product['sku'] ?>',
            qty: '<?= $product['qty'] ?>',
            price: '<?= $product['price'] ?>'
        });
        <?php endforeach; ?>
        IntelliSuggest.inBasket({});
    } catch (err) {
    }
    <?php endif; ?>
</script>
