<?php
/**
 * @var $block \Magento\Checkout\Block\Cart
 * @var $viewModel \Searchspring\Tracking\ViewModel\CartViewModel
 */
?>
<?php $viewModel = $block->getData('searchspring_cart_view_model'); ?>
<?php $searchspringSiteId = $block->escapeHtmlAttr($viewModel->getSearchspringSiteId()); ?>

<?php if (!empty($searchspringSiteId) && !empty($this->getQuote()->getItems())): ?>
    <script type="text/x-magento-init">
        {
            "*": {
            "searchspring-tracking-cart": {
                "siteId": "<?= $searchspringSiteId ?>",
                "products": <?= $viewModel->getProducts($this->getQuote()->getItems()) ?>,
                "sku": <?= $viewModel->getProductsSku() ?>
            }
        }
        }
    </script>
<?php endif; ?>
