<?php
/**
 * @var $block \Magento\Checkout\Block\Onepage\Success
 * @var $viewModel \Searchspring\Tracking\ViewModel\CheckoutViewModel
 */
?>
<?php $viewModel = $block->getData('searchspring_checkout_view_model'); ?>
<?php $searchspringSiteId = $block->escapeHtmlAttr($viewModel->getSearchspringSiteId()); ?>

<?php if (!empty($searchspringSiteId)): ?>
    <script type="text/javascript">
        <?php $products = $viewModel->getProducts(); ?>
        try {
            IntelliSuggest.init({
                siteId: '<?= $searchspringSiteId ?>'
            });
            <?php foreach ($products as $product): ?>
            IntelliSuggest.haveItem({
                sku: '<?= $product['sku'] ?>',
                qty: '<?= $product['qty'] ?>',
                price: '<?= $product['price'] ?>'
            });
            <?php endforeach; ?>
            IntelliSuggest.inSale({});
        } catch (e) {
        }
    </script>
<?php endif; ?>
