<?php
/**
 * @var $block \Magento\Checkout\Block\Onepage\Success
 * @var $viewModel \Searchspring\Tracking\ViewModel\CheckoutViewModel
 */
?>
<?php $viewModel = $block->getData('searchspring_checkout_view_model'); ?>
<?php $searchspringSiteId = $block->escapeHtmlAttr($viewModel->getSearchspringSiteId()); ?>

<script type="text/javascript">
    <?php if (!empty($searchspringSiteId)): ?>
    <?php $products = $viewModel->getProducts(); ?>
    try {
        IntelliSuggest.init({
            siteId: '<?= $searchspringSiteId ?>'
        });
        <?php foreach ($products as $product): ?>
        IntelliSuggest.haveItem({
            sku: '<?= $product['sku'] ?>',
            qty: '<?= $product['qty'] ?>',
            price: '<?= $product['price'] ?>'
        });
        <?php endforeach; ?>
        IntelliSuggest.inSale({});
    } catch (e) {
    }
    <?php endif; ?>
</script>
