<?php
declare(strict_types=1);

use Searchspring\Tracking\ViewModel\Escaper;
use Searchspring\Tracking\ViewModel\GlobalScriptViewModel;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Template $block */
/** @var GlobalScriptViewModel $globalScriptViewModel */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaperViewModel */

$globalScriptViewModel = $block->getGlobalScriptViewModel();
$escaperViewModel = $block->getEscaperViewModel();
$escaper = $escaperViewModel->getEscaper();
if (!$globalScriptViewModel) {
    return;
}

$siteId = $globalScriptViewModel->getSiteId();
$src = $globalScriptViewModel->getTrackingScriptSrc();

if (!$siteId || !$src || !$globalScriptViewModel->shouldRender()) {
    return;
}
?>
<?php
$scriptString = "
    window.athos = window.athos || {};
    window.athos.tracker = window.athos.tracker || {};
    window.athos.tracker.events = window.athos.tracker.events || {};
";
?>

<script siteId="<?= /* @noEscape */ $block->escapeHtmlAttr($siteId) ?>" src="<?= /* @noEscape */ $block->escapeUrl($src) ?>">
    config = { initiator: "magento" };
</script>

<?= /* @noEscape */ $secureRenderer->renderTag(
     'script',
    [
        'type' => 'text/javascript',
        'id' => 'searchspring_init',
    ],
    $scriptString,
    false,
) ?>
