<?php

declare(strict_types=1);

use Searchspring\Tracking\ViewModel\Escaper;
use Searchspring\Tracking\ViewModel\GlobalScriptViewModel;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Template $block */
/** @var GlobalScriptViewModel $globalScriptViewModel */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaperViewModel */

$globalScriptViewModel = $block->getGlobalScriptViewModel();
$escaperViewModel = $block->getEscaperViewModel();
$escaper = $escaperViewModel->getEscaper();
?>
<?php if ($globalScriptViewModel && $globalScriptViewModel->shouldRender()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Searchspring_Tracking/js/pagemeta-cart-tracker": {}
            }
        }
    </script>
<?php endif; ?>
