<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 * @var $viewModel \Searchspring\Tracking\ViewModel\PdpViewModel
 */
?>
<?php $_product = $block->getProduct(); ?>
<?php $sku = $_product->getSku(); ?>
<?php $viewModel = $block->getData('searchspring_pdp_view_model'); ?>
<?php $searchspringSiteId = $block->escapeHtmlAttr($viewModel->getSearchspringSiteId()); ?>

<?php if (!empty($searchspringSiteId)): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "searchspring-tracking-form": {
                    "siteId": "<?= $searchspringSiteId ?>",
                    "sku":    "<?= $sku ?>"
                }
            }
        }
    </script>
<?php endif; ?>
